spring.application.name=fakestoreservice
server.port=8080
spring.datasource.url=jdbc:mysql://fakestore.cfme02qu0zj5.eu-north-1.rds.amazonaws.com:3306/fakestore
spring.datasource.username=admin
spring.datasource.password=Losenord123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
test.value=SANDRA123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver